<a href="https://colab.research.google.com/github/Mehrnoushhk/DeepLearning/blob/master/D2L_Ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf

In [6]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [14]:
print(x.shape)
print(tf.size(x))

(12,)
tf.Tensor(12, shape=(), dtype=int32)


In [8]:
X = tf.reshape(x, (3,4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [15]:
print(X.shape)
print(tf.size(X))

(3, 4)
tf.Tensor(12, shape=(), dtype=int32)


In [19]:
# Create tensore with initial zeros
x = tf.zeros((2,3,4), tf.int32)
x

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>