<a href="https://colab.research.google.com/github/Mehrnoushhk/DeepLearning/blob/master/D2L_Ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf

In [6]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [14]:
print(x.shape)
print(tf.size(x))

(12,)
tf.Tensor(12, shape=(), dtype=int32)


In [8]:
X = tf.reshape(x, (3,4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [15]:
print(X.shape)
print(tf.size(X))

(3, 4)
tf.Tensor(12, shape=(), dtype=int32)


In [19]:
# Create tensore with initial zeros
x = tf.zeros((2,3,4), tf.int32)
x

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

In [20]:
# Create a tensor with elements randomly selected from a normal distribution with mean 0 and standard deviation of 1
x = tf.random.normal((3,4))
x

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.2831727 , -1.1601638 ,  1.2917825 , -0.5016219 ],
       [ 0.65954065, -0.40403718,  0.65235084,  0.7554147 ],
       [-0.81669164,  0.93998396,  0.52293366,  0.17443857]],
      dtype=float32)>

In [26]:
# Concatenate multiple tensors
x = tf.reshape( tf.range(12), (3,4))
y = tf.constant([ [11, 12], [21, 22], [31, 32]])
z = tf.ones((3,3), tf.int32)
tf.concat([x , y, z], axis= 1)


<tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[ 0,  1,  2,  3, 11, 12,  1,  1,  1],
       [ 4,  5,  6,  7, 21, 22,  1,  1,  1],
       [ 8,  9, 10, 11, 31, 32,  1,  1,  1]], dtype=int32)>